### ISSUE TITLE
Contains features and ideas identical to  / directly from Electric w/o credit / mention

### ISSUE THREAD

**Issue by XtremeDevX** [novus-package-manager/novus#3]
From what I have seen, Novus uses a lot of ideas that seem to be copied heavily inspired / directly copied from [Electric](https://github.com/electric-package-manager/electric).

Here are a few examples:

**1. Package Name Autocorrection**

![image](https://user-images.githubusercontent.com/63039748/125489799-f7fe9a09-54bc-4dbf-8e1b-6be04f25dba1.png)

vs
![image](https://user-images.githubusercontent.com/63039748/125489889-059ddfe4-a8f8-4517-b18c-67bcbd09020f.png)

**2. Auto Elevating the User**
![image](https://user-images.githubusercontent.com/63039748/125490073-e1f15c4f-4e36-4739-97b0-c2c1def09b57.png)

vs

![image](https://user-images.githubusercontent.com/63039748/125490121-2dab4132-8985-4998-ba2b-334dae95b24a.png)

**3. Temp Directory Folder Structure**
![image](https://user-images.githubusercontent.com/63039748/125491091-2e2fc424-ab78-4325-8652-d630c6eb33ed.png)

vs

![image](https://user-images.githubusercontent.com/63039748/125491141-5d808d56-4921-40c2-9906-75e5ed3db519.png)

Although it is natural to copy features from direct competitors, it is unethical not to credit or at the least, point out that these features are inspired by Electric. Hope this can be addressed soon 👍.

**Comment by tejas186** [comment]
Um, yes. Giving credit/mention is the least that can be done

**Comment by fullstackslayer** [comment]
I completely agree with you. The Novus website seems heavily inspired by https://hydralite.io and https://covisource.in as well, two projects I worked/am working on. As an open-source project, I understand how this may seem alright to do, however, it's unethical in the face of software development. Please attend to this whenever possible, and at least credit the platforms you were inspired by.

**Comment by Angshu31** [comment]
Most features seem to be very similar - too similar.
Credit should be given at the very least

**Comment by ZaphodElevated** [comment]
I have looked at this issue, and I have given credits to Electric and Chocolatey as it inspired me to build Novus. I have also mentioned hydralite as an inspiration for the website theme

There always might be some similarities in products trying to solve similar problems. For example, atom and sublime text, gimp and photoshop, google docs and ms word, etc will all have similar features.

With this in mind, I assure you that the Novus codebase was developed independently.

**Comment by XtremeDevX** [comment]
@ZaphodElevated thanks for looking into this - would appreciate if you could link the `CREDITS.md` to the readme under a credits heading, most people end up going through the README instead of casually browsing code files.
